### ISSUE TITLE
Getting error when clicking test 

### ISSUE THREAD

**Issue by pologc** [albertogeniola/SSIS-Json-Source-Component#1]
getting below error when clicking test
"Sorry, this functionality is still under development!"

**Comment by albertogeniola** [comment]
That is not an error. That feature is under development for now.

**Comment by pologc** [comment]
Hi Alberto, 
I have used the manual steps to register the libraries into GAC. I can see the source component in SSIS. Followed the steps to create a sample package to read a JSON file (GET method). I though I need to click Test to parse the JSON file and that's where I am stuck. Am I doing something wrong here?
Thanks, 
Jai
